CREATE TABLE Countries(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Customers(
	Id INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	Gender VARCHAR(1) NOT NULL CHECK(Gender = 'M' OR Gender = 'F'),
	Age INT NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL CHECK(DATALENGTH(PhoneNumber) = 10),
	CountryId INT FOREIGN KEY REFERENCES Countries(Id)
)

CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(25) UNIQUE NOT NULL,
	[Description] VARCHAR(250) NOT NULL,
	Recipe VARCHAR(MAX) NOT NULL,
	Price MONEY NOT NULL CHECK(Price >= 0)
)

CREATE TABLE Feedbacks(
	Id INT PRIMARY KEY IDENTITY,
	[Description] VARCHAR(255) NOT NULL,
	Rate DECIMAL(2) NOT NULL CHECK(Rate BETWEEN 0 AND 10),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id),
	CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customers(Id)
)

CREATE TABLE Distributors(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(25) NOT NULL UNIQUE,
	AddressText VARCHAR(30) NOT NULL,
	Summary VARCHAR(200) NOT NULL,
	CountryId INT NOT NULL FOREIGN KEY REFERENCES Countries(Id)
) 

CREATE TABLE Ingredients(
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(30) NOT NULL,
	[Description] VARCHAR(200) NOT NULL,
	OriginCountryId INT NOT NULL FOREIGN KEY REFERENCES Countries(Id),
	DistributorId INT NOT NULL FOREIGN KEY REFERENCES Distributors(Id)
)

CREATE TABLE ProductsIngredients(
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id),
	IngredientId INT NOT NULL FOREIGN KEY REFERENCES Ingredients(Id),
	PRIMARY KEY(ProductId,IngredientId)
)