CREATE TABLE Categories (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(10) NOT NULL
)

CREATE TABLE Countries(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(10) NOT NULL
)

CREATE TABLE Vendors(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(25) NOT NULL,
	NumberVAT VARCHAR(15) NOT NULL,
	AddressId INT NOT NULL
)

CREATE TABLE Clients(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(25) NOT NULL,
	AddressId INT NOT NULL
)

CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(35) NOT NULL,
	Price DECIMAL(18,2) NOT NULL,
	CategoryId INT NOT NULL
	FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
	VendorId INT NOT NULL
	FOREIGN KEY (VendorId) REFERENCES Vendors(Id)
)

CREATE TABLE ProductsClients( 
	ProductId INT NOT NULL
	FOREIGN KEY (ProductId) REFERENCES Products(Id),
	ClientId INT NOT NULL
	FOREIGN KEY (ClientId) REFERENCES Clients(Id),
	CONSTRAINT PK_ProductClients PRIMARY KEY (ProductId,ClientId)
)

CREATE TABLE Invoices(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Number INT UNIQUE NOT NULL,
	IssueDate DATETIME2 NOT NULL,
	DueDate DATETIME2 NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	Currency VARCHAR(5) NOT NULL,
	ClientId INT NOT NULL
	FOREIGN KEY (ClientId) REFERENCES Clients(Id)
)

CREATE TABLE Addresses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	StreetName VARCHAR(20) NOT NULL,
	StreetNumber INT NOT NULL,
	PostCode INT NOT NULL,
	City VARCHAR(25) NOT NULL,
	CountryId INT NOT NULL
	FOREIGN KEY (CountryId) REFERENCES Countries(Id)
)

ALTER TABLE Vendors
ADD FOREIGN KEY (AddressId) REFERENCES Addresses(Id)

ALTER TABLE Clients
ADD FOREIGN KEY (AddressId) REFERENCES Addresses(Id)