CREATE TABLE Sizes (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Length INT NOT NULL CHECK(Length > 10 AND Length < 25),
	RingRange DECIMAL NOT NULL CHECK(RingRange > 1.5 AND RingRange < 7.5)
)

CREATE TABLE Tastes (
	Id INT PRIMARY KEY IDENTITY,
	TasteType VARCHAR(20) NOT NULL,
	TasteStrength VARCHAR(15) NOT NULL,
	ImageURL VARBINARY(100) NOT NULL
)

CREATE TABLE Brands (
	Id INT PRIMARY KEY IDENTITY,
	BrandName VARCHAR(30) UNIQUE NOT NULL,
	BrandDescription VARCHAR(MAX) NOT NULL
)

CREATE TABLE Cigars(
	Id INT PRIMARY KEY IDENTITY,
	CigarName VARCHAR(80) NOT NULL,
	BrandId	INT NOT NULL 
	FOREIGN KEY (BrandId) REFERENCES Brands(Id),
	TastId INT NOT NULL
	FOREIGN KEY (TastId) REFERENCES Tastes(Id),
	SizeId INT NOT NULL
	FOREIGN KEY (SizeId) REFERENCES Sizes(Id),
	PriceForSingleCigar DECIMAL(19,4) NOT NULL,
	ImageURL VARBINARY(100) NOT NULL
)

CREATE TABLE Addresses(
	Id INT PRIMARY KEY IDENTITY,
	Town VARCHAR(30) NOT NULL,
	Country VARCHAR(30) NOT NULL,
	Streat VARCHAR(100) NOT NULL,
	ZIP VARCHAR(320) NOT NULL
)

CREATE TABLE Clients(
	Id INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	AddressId INT NOT NULL
	FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
)

CREATE TABLE ClientsCigars(
	ClientId INT
	FOREIGN KEY (ClientId) REFERENCES Clients(Id),
	CigarId INT
	FOREIGN KEY (CigarId) REFERENCES Cigars(Id),
	CONSTRAINT PK_ClientsCigars PRIMARY KEY (ClientId,CigarId)
)